/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: v4.0.12.2823
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddSeriesOptions {
    #[serde(rename = "ignoreEpisodesWithFiles", skip_serializing_if = "Option::is_none")]
    pub ignore_episodes_with_files: Option<bool>,
    #[serde(rename = "ignoreEpisodesWithoutFiles", skip_serializing_if = "Option::is_none")]
    pub ignore_episodes_without_files: Option<bool>,
    #[serde(rename = "monitor", skip_serializing_if = "Option::is_none")]
    pub monitor: Option<models::MonitorTypes>,
    #[serde(rename = "searchForMissingEpisodes", skip_serializing_if = "Option::is_none")]
    pub search_for_missing_episodes: Option<bool>,
    #[serde(rename = "searchForCutoffUnmetEpisodes", skip_serializing_if = "Option::is_none")]
    pub search_for_cutoff_unmet_episodes: Option<bool>,
}

impl AddSeriesOptions {
    pub fn new() -> AddSeriesOptions {
        AddSeriesOptions {
            ignore_episodes_with_files: None,
            ignore_episodes_without_files: None,
            monitor: None,
            search_for_missing_episodes: None,
            search_for_cutoff_unmet_episodes: None,
        }
    }
}

