/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: v4.0.12.2823
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticationRequiredType {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabledForLocalAddresses")]
    DisabledForLocalAddresses,

}

impl std::fmt::Display for AuthenticationRequiredType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Enabled => write!(f, "enabled"),
            Self::DisabledForLocalAddresses => write!(f, "disabledForLocalAddresses"),
        }
    }
}

impl Default for AuthenticationRequiredType {
    fn default() -> AuthenticationRequiredType {
        Self::Enabled
    }
}

