/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: v4.0.12.2823
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFormatResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "includeCustomFormatWhenRenaming", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub include_custom_format_when_renaming: Option<Option<bool>>,
    #[serde(rename = "specifications", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub specifications: Option<Option<Vec<models::CustomFormatSpecificationSchema>>>,
}

impl CustomFormatResource {
    pub fn new() -> CustomFormatResource {
        CustomFormatResource {
            id: None,
            name: None,
            include_custom_format_when_renaming: None,
            specifications: None,
        }
    }
}

