/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: v4.0.12.2823
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadClientConfigResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "downloadClientWorkingFolders", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub download_client_working_folders: Option<Option<String>>,
    #[serde(rename = "enableCompletedDownloadHandling", skip_serializing_if = "Option::is_none")]
    pub enable_completed_download_handling: Option<bool>,
    #[serde(rename = "autoRedownloadFailed", skip_serializing_if = "Option::is_none")]
    pub auto_redownload_failed: Option<bool>,
    #[serde(rename = "autoRedownloadFailedFromInteractiveSearch", skip_serializing_if = "Option::is_none")]
    pub auto_redownload_failed_from_interactive_search: Option<bool>,
}

impl DownloadClientConfigResource {
    pub fn new() -> DownloadClientConfigResource {
        DownloadClientConfigResource {
            id: None,
            download_client_working_folders: None,
            enable_completed_download_handling: None,
            auto_redownload_failed: None,
            auto_redownload_failed_from_interactive_search: None,
        }
    }
}

