/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: v4.0.12.2823
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FileDateType {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "localAirDate")]
    LocalAirDate,
    #[serde(rename = "utcAirDate")]
    UtcAirDate,

}

impl std::fmt::Display for FileDateType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::LocalAirDate => write!(f, "localAirDate"),
            Self::UtcAirDate => write!(f, "utcAirDate"),
        }
    }
}

impl Default for FileDateType {
    fn default() -> FileDateType {
        Self::None
    }
}

