/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: v4.0.12.2823
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImportListType {
    #[serde(rename = "program")]
    Program,
    #[serde(rename = "plex")]
    Plex,
    #[serde(rename = "trakt")]
    Trakt,
    #[serde(rename = "simkl")]
    Simkl,
    #[serde(rename = "other")]
    Other,
    #[serde(rename = "advanced")]
    Advanced,

}

impl std::fmt::Display for ImportListType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Program => write!(f, "program"),
            Self::Plex => write!(f, "plex"),
            Self::Trakt => write!(f, "trakt"),
            Self::Simkl => write!(f, "simkl"),
            Self::Other => write!(f, "other"),
            Self::Advanced => write!(f, "advanced"),
        }
    }
}

impl Default for ImportListType {
    fn default() -> ImportListType {
        Self::Program
    }
}

