/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: v4.0.12.2823
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MonitoringOptions {
    #[serde(rename = "ignoreEpisodesWithFiles", skip_serializing_if = "Option::is_none")]
    pub ignore_episodes_with_files: Option<bool>,
    #[serde(rename = "ignoreEpisodesWithoutFiles", skip_serializing_if = "Option::is_none")]
    pub ignore_episodes_without_files: Option<bool>,
    #[serde(rename = "monitor", skip_serializing_if = "Option::is_none")]
    pub monitor: Option<models::MonitorTypes>,
}

impl MonitoringOptions {
    pub fn new() -> MonitoringOptions {
        MonitoringOptions {
            ignore_episodes_with_files: None,
            ignore_episodes_without_files: None,
            monitor: None,
        }
    }
}

