/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: v4.0.12.2823
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueueStatusResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "totalCount", skip_serializing_if = "Option::is_none")]
    pub total_count: Option<i32>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "unknownCount", skip_serializing_if = "Option::is_none")]
    pub unknown_count: Option<i32>,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<bool>,
    #[serde(rename = "warnings", skip_serializing_if = "Option::is_none")]
    pub warnings: Option<bool>,
    #[serde(rename = "unknownErrors", skip_serializing_if = "Option::is_none")]
    pub unknown_errors: Option<bool>,
    #[serde(rename = "unknownWarnings", skip_serializing_if = "Option::is_none")]
    pub unknown_warnings: Option<bool>,
}

impl QueueStatusResource {
    pub fn new() -> QueueStatusResource {
        QueueStatusResource {
            id: None,
            total_count: None,
            count: None,
            unknown_count: None,
            errors: None,
            warnings: None,
            unknown_errors: None,
            unknown_warnings: None,
        }
    }
}

