/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: v4.0.12.2823
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RemotePathMappingResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "host", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub host: Option<Option<String>>,
    #[serde(rename = "remotePath", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remote_path: Option<Option<String>>,
    #[serde(rename = "localPath", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub local_path: Option<Option<String>>,
}

impl RemotePathMappingResource {
    pub fn new() -> RemotePathMappingResource {
        RemotePathMappingResource {
            id: None,
            host: None,
            remote_path: None,
            local_path: None,
        }
    }
}

