/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: v4.0.12.2823
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SeriesTypes {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "daily")]
    Daily,
    #[serde(rename = "anime")]
    Anime,

}

impl std::fmt::Display for SeriesTypes {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Standard => write!(f, "standard"),
            Self::Daily => write!(f, "daily"),
            Self::Anime => write!(f, "anime"),
        }
    }
}

impl Default for SeriesTypes {
    fn default() -> SeriesTypes {
        Self::Standard
    }
}

