/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: v4.0.12.2823
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SeriesStatusType {
    #[serde(rename = "continuing")]
    Continuing,
    #[serde(rename = "ended")]
    Ended,
    #[serde(rename = "upcoming")]
    Upcoming,
    #[serde(rename = "deleted")]
    Deleted,

}

impl std::fmt::Display for SeriesStatusType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Continuing => write!(f, "continuing"),
            Self::Ended => write!(f, "ended"),
            Self::Upcoming => write!(f, "upcoming"),
            Self::Deleted => write!(f, "deleted"),
        }
    }
}

impl Default for SeriesStatusType {
    fn default() -> SeriesStatusType {
        Self::Continuing
    }
}

