/*
 * Sonarr
 *
 * Sonarr API docs - The v3 API docs apply to both v3 and v4 versions of Sonarr. Some functionality may only be available in v4 of the Sonarr application.
 *
 * The version of the OpenAPI document: v4.0.12.2823
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateChanges {
    #[serde(rename = "new", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub new: Option<Option<Vec<String>>>,
    #[serde(rename = "fixed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fixed: Option<Option<Vec<String>>>,
}

impl UpdateChanges {
    pub fn new() -> UpdateChanges {
        UpdateChanges {
            new: None,
            fixed: None,
        }
    }
}

